# Module 6 - NumPy examples #

NumPy: A library related to processing large-quantities of numbers

When we are working with libraries, we need to import them into our code. After importing them we are allowed to use the functions they contain.

In the case of `numpy` we can import by using the line:

`import numpy as np`

which means: everytime we use `np.` before calling a function, it belong to the `numpy` library. See example below:

In [3]:
import numpy as np

array1D = np.array([1,2,3,4,5])
print(array1D[0])

array2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2D[1,3])

1
9


To create a 4x5 array/matrix of zeroes or random values

In [5]:
zeroMatrix = np.zeros((2,5))  # note the double brackets
randomMatrix1 = np.random.random((4,5)) # range: [0,1]
print(zeroMatrix)
print(randomMatrix1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.60969402 0.76070089 0.54055897 0.49081694 0.14607895]
 [0.9274379  0.4689054  0.65369193 0.81767634 0.23969071]
 [0.86362905 0.63565638 0.86327216 0.73167728 0.81917222]
 [0.64470348 0.3206902  0.43235767 0.72365108 0.83728364]]


In [13]:
digits = np.arange(0, 10, 1)
evens = np.arange(0, 100, 2)
byHalf = np.arange(0, 10, 0.5)
print(digits)
print(evens)
print(byHalf)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [21]:
list = np.linspace(0, 10, 50)       # 50 data points
xCoords = np.linspace(0, 2*np.pi, 100) # 100 data points
print(list)
print(xCoords)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 

In [19]:
xCoords = np.linspace(0, 2 * np.pi, 100)
yCoords = np.sin(xCoords)
print(np.array([1,2,3]) * 2)   # [2,4,6]

[2 4 6]


In [22]:
matrix = np.array([[1,2,3],[7,9,8],[6,5,4]])
print(matrix.min())    # 1
print(matrix.max())    # 9
print(matrix.sum())    # 45

1
9
45


In [23]:
matrix = np.array([[1,2,3],[7,9,8],[6,5,4]])
print(matrix.min(axis=0))   # column minimum:     [1,2,3]
print(matrix.max(axis=1))   # row maximum:        [3,9,6]
print(matrix.sum(axis=1))   # row sum:            [6,24,15]

[1 2 3]
[3 9 6]
[ 6 24 15]


In [25]:
matrix = np.array([[1,2,3],[7,9,8],[6,5,4]])
for row in matrix:
    print(row)

[1 2 3]
[7 9 8]
[6 5 4]


In [27]:
list = [1,2,3,4,5,6,7,8,9]
np.random.shuffle(list)
print('Shuffled:', list)

Shuffled: [8, 9, 6, 7, 1, 5, 3, 4, 2]


In [28]:
coeff = np.array([[2,4,3],
                  [1,5,1],
                  [3,2,2]])
vals = np.array([5,8,4])
print('Solutions:', np.linalg.solve(coeff, vals))
# [1.05263158 1.63157895 -1.21052632]

Solutions: [ 1.05263158  1.63157895 -1.21052632]


## Reading/ Saving data to a file ##

In [7]:
vals = np.loadtxt(fname='matrix-example1.txt', delimiter=',', dtype='i')
print(vals)
# [[1,2,3],
#  [4,5,6],
#  [7,8,9]]

[[1 2 3 8]
 [4 5 6 8]
 [7 8 9 8]]


In [8]:
data = np.genfromtxt('data-example1.txt', dtype=None, delimiter=",")
print(data)
# [[1, 2, 224690, 5.97222057420059, 'K3V', 0.999]
#  [2, 3, 224699, -1.1464684004746, 'B9', -0.019]]

[(1, 2, 224690,  5.97222057, b" 'K3V'",  0.999, 7)
 (2, 3, 224699, -1.1464684 , b" 'B9'", -0.019, 6)]


<ipython-input-8-5699d58b5176>:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data = np.genfromtxt('data-example1.txt', dtype=None, delimiter=",")


In [12]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
np.savetxt(fname='data1.txt', delimiter=',', X=array, fmt='%d')